/*
 * (C) Copyright IBM Corp. 2026.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

/*
 * IBM OpenAPI SDK Code Generator Version: 3.113.1-d76630af-20260320-135953
 */

package com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1;

import com.google.gson.JsonObject;
import com.ibm.cloud.drautomation_sdk.common.SdkCommon;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.ApiKeyResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.ClusterNodeResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.CreateApiKeyOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.CreateClusterNodeOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.CreatePhaDeploymentOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.DeleteClusterNodeOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.DownloadPhaAgentFileOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetClusterNodeOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetPhaAgentFileDownloadJobStatusOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetPhaDeploymentOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetPhaLastOperationOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetPowervsWorkspaceOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.GetSupportedLocationOptions;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.PhaAgentJobStatusResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.PhaDeploymentResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.PhaSupportedLocationsResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.PhaWorkspacesRegionResponse;
import com.ibm.cloud.drautomation_sdk.powerha_automation_service.v1.model.ServiceInstancePhaStatus;
import com.ibm.cloud.sdk.core.http.RequestBuilder;
import com.ibm.cloud.sdk.core.http.ResponseConverter;
import com.ibm.cloud.sdk.core.http.ServiceCall;
import com.ibm.cloud.sdk.core.security.Authenticator;
import com.ibm.cloud.sdk.core.security.ConfigBasedAuthenticatorFactory;
import com.ibm.cloud.sdk.core.service.BaseService;
import com.ibm.cloud.sdk.core.util.ResponseConverterUtils;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator).
 *
 * API Version: 1.0.0
 */
public class PowerhaAutomationService extends BaseService {

  /**
   * Default service name used when configuring the `PowerhaAutomationService` client.
   */
  public static final String DEFAULT_SERVICE_NAME = "powerha_automation_service";

  /**
   * Default service endpoint URL.
   */
  public static final String DEFAULT_SERVICE_URL = "https://power-dra.cloud.ibm.com";

 /**
   * Class method which constructs an instance of the `PowerhaAutomationService` client.
   * The default service name is used to configure the client instance.
   *
   * @return an instance of the `PowerhaAutomationService` client using external configuration
   */
  public static PowerhaAutomationService newInstance() {
    return newInstance(DEFAULT_SERVICE_NAME);
  }

  /**
   * Class method which constructs an instance of the `PowerhaAutomationService` client.
   * The specified service name is used to configure the client instance.
   *
   * @param serviceName the service name to be used when configuring the client instance
   * @return an instance of the `PowerhaAutomationService` client using external configuration
   */
  public static PowerhaAutomationService newInstance(String serviceName) {
    Authenticator authenticator = ConfigBasedAuthenticatorFactory.getAuthenticator(serviceName);
    PowerhaAutomationService service = new PowerhaAutomationService(serviceName, authenticator);
    service.configureService(serviceName);
    return service;
  }

  /**
   * Constructs an instance of the `PowerhaAutomationService` client.
   * The specified service name and authenticator are used to configure the client instance.
   *
   * @param serviceName the service name to be used when configuring the client instance
   * @param authenticator the {@link Authenticator} instance to be configured for this client
   */
  public PowerhaAutomationService(String serviceName, Authenticator authenticator) {
    super(serviceName, authenticator);
    setServiceUrl(DEFAULT_SERVICE_URL);
  }

  /**
   * Update the apikey for the specified PowerHA service instance.
   *
   * Updates a new apikey for the specified PowerHA service instance.
   *
   * @param createApiKeyOptions the {@link CreateApiKeyOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ApiKeyResponse}
   */
  public ServiceCall<ApiKeyResponse> createApiKey(CreateApiKeyOptions createApiKeyOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createApiKeyOptions,
      "createApiKeyOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", createApiKeyOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/api_key/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "createApiKey");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (createApiKeyOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", createApiKeyOptions.acceptLanguage());
    }
    final JsonObject contentJson = new JsonObject();
    if (createApiKeyOptions.apiKey() != null) {
      contentJson.addProperty("api_key", createApiKeyOptions.apiKey());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<ApiKeyResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ApiKeyResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves the cluster node details for the specified PowerHA instance.
   *
   * Retrieves details of all cluster nodes configured for the given PowerHA service instance.
   *
   * @param getClusterNodeOptions the {@link GetClusterNodeOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ClusterNodeResponse}
   */
  public ServiceCall<ClusterNodeResponse> getClusterNode(GetClusterNodeOptions getClusterNodeOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getClusterNodeOptions,
      "getClusterNodeOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getClusterNodeOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/cluster_nodes/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getClusterNode");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getClusterNodeOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getClusterNodeOptions.ifNoneMatch());
    }
    ResponseConverter<ClusterNodeResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ClusterNodeResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Add a new cluster node.
   *
   * Adds a new node to the PowerHA cluster for the specified PowerHA service instance.
   *
   * @param createClusterNodeOptions the {@link CreateClusterNodeOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ClusterNodeResponse}
   */
  public ServiceCall<ClusterNodeResponse> createClusterNode(CreateClusterNodeOptions createClusterNodeOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createClusterNodeOptions,
      "createClusterNodeOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", createClusterNodeOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/cluster_nodes/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "createClusterNode");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (createClusterNodeOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", createClusterNodeOptions.acceptLanguage());
    }
    if (createClusterNodeOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", createClusterNodeOptions.ifNoneMatch());
    }
    final JsonObject contentJson = new JsonObject();
    contentJson.add("primary_cluster_nodes", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createClusterNodeOptions.primaryClusterNodes()));
    if (createClusterNodeOptions.secondaryClusterNodes() != null) {
      contentJson.add("secondary_cluster_nodes", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createClusterNodeOptions.secondaryClusterNodes()));
    }
    builder.bodyJson(contentJson);
    ResponseConverter<ClusterNodeResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ClusterNodeResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Delete a cluster node.
   *
   * Removes the specified cluster node from the PowerHA service instance.
   *
   * @param deleteClusterNodeOptions the {@link DeleteClusterNodeOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ClusterNodeResponse}
   */
  public ServiceCall<ClusterNodeResponse> deleteClusterNode(DeleteClusterNodeOptions deleteClusterNodeOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(deleteClusterNodeOptions,
      "deleteClusterNodeOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", deleteClusterNodeOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.delete(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/cluster_nodes/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "deleteClusterNode");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (deleteClusterNodeOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", deleteClusterNodeOptions.ifNoneMatch());
    }
    builder.query("vm_id", String.valueOf(deleteClusterNodeOptions.vmId()));
    ResponseConverter<ClusterNodeResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ClusterNodeResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List of PowerVS workspaces based on location.
   *
   * Retrieves list of powerVS workspaces related to the PowerHA service instance based on location.
   *
   * @param getPowervsWorkspaceOptions the {@link GetPowervsWorkspaceOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link PhaWorkspacesRegionResponse}
   */
  public ServiceCall<PhaWorkspacesRegionResponse> getPowervsWorkspace(GetPowervsWorkspaceOptions getPowervsWorkspaceOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getPowervsWorkspaceOptions,
      "getPowervsWorkspaceOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getPowervsWorkspaceOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/powervs_workspaces/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getPowervsWorkspace");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getPowervsWorkspaceOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getPowervsWorkspaceOptions.acceptLanguage());
    }
    if (getPowervsWorkspaceOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getPowervsWorkspaceOptions.ifNoneMatch());
    }
    builder.query("location_id", String.valueOf(getPowervsWorkspaceOptions.locationId()));
    ResponseConverter<PhaWorkspacesRegionResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<PhaWorkspacesRegionResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * View details of the last operation performed on the PowerHA instance.
   *
   * Retrieves the most recent operation performed on the PowerHA service instance.
   *
   * @param getPhaLastOperationOptions the {@link GetPhaLastOperationOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ServiceInstancePhaStatus}
   */
  public ServiceCall<ServiceInstancePhaStatus> getPhaLastOperation(GetPhaLastOperationOptions getPhaLastOperationOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getPhaLastOperationOptions,
      "getPhaLastOperationOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getPhaLastOperationOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/last_operation/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getPhaLastOperation");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getPhaLastOperationOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getPhaLastOperationOptions.acceptLanguage());
    }
    if (getPhaLastOperationOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getPhaLastOperationOptions.ifNoneMatch());
    }
    ResponseConverter<ServiceInstancePhaStatus> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ServiceInstancePhaStatus>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Retrieves deployment details.
   *
   * Retrieves the PowerHA deployment configuration, status, and associated metadata.
   *
   * @param getPhaDeploymentOptions the {@link GetPhaDeploymentOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link PhaDeploymentResponse}
   */
  public ServiceCall<PhaDeploymentResponse> getPhaDeployment(GetPhaDeploymentOptions getPhaDeploymentOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getPhaDeploymentOptions,
      "getPhaDeploymentOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getPhaDeploymentOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/pha_deployment/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getPhaDeployment");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getPhaDeploymentOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getPhaDeploymentOptions.ifNoneMatch());
    }
    ResponseConverter<PhaDeploymentResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<PhaDeploymentResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Create a new deployment.
   *
   * Create a new PowerHA deployment for a given location and PowerVS workspace. Refer deploying the PowerHA on Powervs
   * https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-getting-started-with-ha-automation-for-power-virtual-server
   * for more details.
   *
   * @param createPhaDeploymentOptions the {@link CreatePhaDeploymentOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link PhaDeploymentResponse}
   */
  public ServiceCall<PhaDeploymentResponse> createPhaDeployment(CreatePhaDeploymentOptions createPhaDeploymentOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createPhaDeploymentOptions,
      "createPhaDeploymentOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", createPhaDeploymentOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/pha_deployment/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "createPhaDeployment");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (createPhaDeploymentOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", createPhaDeploymentOptions.acceptLanguage());
    }
    if (createPhaDeploymentOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", createPhaDeploymentOptions.ifNoneMatch());
    }
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("location_id", createPhaDeploymentOptions.locationId());
    contentJson.addProperty("primary_workspace", createPhaDeploymentOptions.primaryWorkspace());
    if (createPhaDeploymentOptions.apiKey() != null) {
      contentJson.addProperty("api_key", createPhaDeploymentOptions.apiKey());
    }
    if (createPhaDeploymentOptions.clusterType() != null) {
      contentJson.addProperty("cluster_type", createPhaDeploymentOptions.clusterType());
    }
    if (createPhaDeploymentOptions.configureType() != null) {
      contentJson.addProperty("configure_type", createPhaDeploymentOptions.configureType());
    }
    if (createPhaDeploymentOptions.primaryClusterNodes() != null) {
      contentJson.add("primary_cluster_nodes", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createPhaDeploymentOptions.primaryClusterNodes()));
    }
    if (createPhaDeploymentOptions.standbyClusterNodes() != null) {
      contentJson.add("standby_cluster_nodes", com.ibm.cloud.sdk.core.util.GsonSingleton.getGson().toJsonTree(createPhaDeploymentOptions.standbyClusterNodes()));
    }
    if (createPhaDeploymentOptions.primaryLocation() != null) {
      contentJson.addProperty("primary_location", createPhaDeploymentOptions.primaryLocation());
    }
    if (createPhaDeploymentOptions.secondaryLocation() != null) {
      contentJson.addProperty("secondary_location", createPhaDeploymentOptions.secondaryLocation());
    }
    if (createPhaDeploymentOptions.secondaryWorkspace() != null) {
      contentJson.addProperty("secondary_workspace", createPhaDeploymentOptions.secondaryWorkspace());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<PhaDeploymentResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<PhaDeploymentResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get PowerVS locations.
   *
   * Retrieves the list of PowerVS locations where PowerHA service is supported.
   *
   * @param getSupportedLocationOptions the {@link GetSupportedLocationOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link PhaSupportedLocationsResponse}
   */
  public ServiceCall<PhaSupportedLocationsResponse> getSupportedLocation(GetSupportedLocationOptions getSupportedLocationOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getSupportedLocationOptions,
      "getSupportedLocationOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getSupportedLocationOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/supported_locations/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getSupportedLocation");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getSupportedLocationOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getSupportedLocationOptions.ifNoneMatch());
    }
    ResponseConverter<PhaSupportedLocationsResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<PhaSupportedLocationsResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get the Job status of the downloaded powerHA agent file.
   *
   * Returns the current status of the job associated with a PowerHA agent file download. It indicates whether the
   * download job is in running, completed, or failed, along with relevant metadata such as job ID, Job creation time
   * and last updated time.
   *
   * @param getPhaAgentFileDownloadJobStatusOptions the {@link GetPhaAgentFileDownloadJobStatusOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link PhaAgentJobStatusResponse}
   */
  public ServiceCall<PhaAgentJobStatusResponse> getPhaAgentFileDownloadJobStatus(GetPhaAgentFileDownloadJobStatusOptions getPhaAgentFileDownloadJobStatusOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getPhaAgentFileDownloadJobStatusOptions,
      "getPhaAgentFileDownloadJobStatusOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", getPhaAgentFileDownloadJobStatusOptions.phaInstanceId());
    pathParamsMap.put("pha_job_id", getPhaAgentFileDownloadJobStatusOptions.phaJobId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/pha_agent/download/{pha_instance_id}/jobs/{pha_job_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "getPhaAgentFileDownloadJobStatus");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getPhaAgentFileDownloadJobStatusOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getPhaAgentFileDownloadJobStatusOptions.acceptLanguage());
    }
    if (getPhaAgentFileDownloadJobStatusOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", getPhaAgentFileDownloadJobStatusOptions.ifNoneMatch());
    }
    ResponseConverter<PhaAgentJobStatusResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<PhaAgentJobStatusResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Downloads PowerHA Agent file.
   *
   * Validates the pvm instance and then creates a job for the download process, downloads the PowerHA agent file from
   * the Cloud Object Storage (COS) location, and updates the job progress in real time. Users can use the job ID to
   * query the download status, including whether the job is running, completed, or failed.
   *
   * @param downloadPhaAgentFileOptions the {@link DownloadPhaAgentFileOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link InputStream}
   */
  public ServiceCall<InputStream> downloadPhaAgentFile(DownloadPhaAgentFileOptions downloadPhaAgentFileOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(downloadPhaAgentFileOptions,
      "downloadPhaAgentFileOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("pha_instance_id", downloadPhaAgentFileOptions.phaInstanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/powerha_automation/v1/pha_agent/download/{pha_instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("powerha_automation_service", "v1", "downloadPhaAgentFile");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/octet-stream");
    if (downloadPhaAgentFileOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", downloadPhaAgentFileOptions.acceptLanguage());
    }
    if (downloadPhaAgentFileOptions.ifNoneMatch() != null) {
      builder.header("If-None-Match", downloadPhaAgentFileOptions.ifNoneMatch());
    }
    ResponseConverter<InputStream> responseConverter = ResponseConverterUtils.getInputStream();
    return createServiceCall(builder.build(), responseConverter);
  }

}
