/*
 * (C) Copyright IBM Corp. 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

/*
 * IBM OpenAPI SDK Code Generator Version: 3.108.0-56772134-20251111-102802
 */

package com.ibm.cloud.drautomation_sdk.dr_automation_service.v1;

import com.google.gson.JsonObject;
import com.ibm.cloud.drautomation_sdk.common.SdkCommon;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.CreateManageDrOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.DrAutomationGetSummaryResponse;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.DrData;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.Event;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.EventCollection;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetDrGrsLocationPairOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetDrLocationsOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetDrLocationsResponse;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetDrManagedVmOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetDrSummaryOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetEventOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetGRSLocationPairResponse;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetLastOperationOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetMachineTypeOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.GetPowervsWorkspacesOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.ListEventsOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.MachineTypesByWorkspace;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.ManagedVmMapResponse;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.ServiceInstanceManageDR;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.ServiceInstanceStatus;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.UpdateApikeyOptions;
import com.ibm.cloud.drautomation_sdk.dr_automation_service.v1.model.ValidationKeyResponse;
import com.ibm.cloud.sdk.core.http.RequestBuilder;
import com.ibm.cloud.sdk.core.http.ResponseConverter;
import com.ibm.cloud.sdk.core.http.ServiceCall;
import com.ibm.cloud.sdk.core.security.Authenticator;
import com.ibm.cloud.sdk.core.security.ConfigBasedAuthenticatorFactory;
import com.ibm.cloud.sdk.core.service.BaseService;
import com.ibm.cloud.sdk.core.util.ResponseConverterUtils;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator).
 *
 * API Version: 0.0.1
 */
public class DrAutomationService extends BaseService {

  /**
   * Default service name used when configuring the `DrAutomationService` client.
   */
  public static final String DEFAULT_SERVICE_NAME = "dr_automation_service";

  /**
   * Default service endpoint URL.
   */
  public static final String DEFAULT_SERVICE_URL = "https://power-dra.cloud.ibm.com";

 /**
   * Class method which constructs an instance of the `DrAutomationService` client.
   * The default service name is used to configure the client instance.
   *
   * @return an instance of the `DrAutomationService` client using external configuration
   */
  public static DrAutomationService newInstance() {
    return newInstance(DEFAULT_SERVICE_NAME);
  }

  /**
   * Class method which constructs an instance of the `DrAutomationService` client.
   * The specified service name is used to configure the client instance.
   *
   * @param serviceName the service name to be used when configuring the client instance
   * @return an instance of the `DrAutomationService` client using external configuration
   */
  public static DrAutomationService newInstance(String serviceName) {
    Authenticator authenticator = ConfigBasedAuthenticatorFactory.getAuthenticator(serviceName);
    DrAutomationService service = new DrAutomationService(serviceName, authenticator);
    service.configureService(serviceName);
    return service;
  }

  /**
   * Constructs an instance of the `DrAutomationService` client.
   * The specified service name and authenticator are used to configure the client instance.
   *
   * @param serviceName the service name to be used when configuring the client instance
   * @param authenticator the {@link Authenticator} instance to be configured for this client
   */
  public DrAutomationService(String serviceName, Authenticator authenticator) {
    super(serviceName, authenticator);
    setServiceUrl(DEFAULT_SERVICE_URL);
  }

  /**
   * Updates the API key for the specified service instance.
   *
   * Updating the current API key details for the specified service instance.
   *
   * @param updateApikeyOptions the {@link UpdateApikeyOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ValidationKeyResponse}
   */
  public ServiceCall<ValidationKeyResponse> updateApikey(UpdateApikeyOptions updateApikeyOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(updateApikeyOptions,
      "updateApikeyOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", updateApikeyOptions.instanceId());
    RequestBuilder builder = RequestBuilder.put(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/apikey/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "updateApikey");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (updateApikeyOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", updateApikeyOptions.acceptLanguage());
    }
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("api_key", updateApikeyOptions.apiKey());
    builder.bodyJson(contentJson);
    ResponseConverter<ValidationKeyResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ValidationKeyResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get GRS location pairs based on managed vms.
   *
   * Retrieves the (GRS) location pairs associated with the specified service instance based on managed VMs.
   *
   * @param getDrGrsLocationPairOptions the {@link GetDrGrsLocationPairOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link GetGRSLocationPairResponse}
   */
  public ServiceCall<GetGRSLocationPairResponse> getDrGrsLocationPair(GetDrGrsLocationPairOptions getDrGrsLocationPairOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getDrGrsLocationPairOptions,
      "getDrGrsLocationPairOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getDrGrsLocationPairOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/dr_grs_location_pairs/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getDrGrsLocationPair");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getDrGrsLocationPairOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getDrGrsLocationPairOptions.acceptLanguage());
    }
    ResponseConverter<GetGRSLocationPairResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<GetGRSLocationPairResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get Disaster recovery locations.
   *
   * Retrieves the list of disaster recovery (DR) locations available for the specified service instance.
   *
   * @param getDrLocationsOptions the {@link GetDrLocationsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link GetDrLocationsResponse}
   */
  public ServiceCall<GetDrLocationsResponse> getDrLocations(GetDrLocationsOptions getDrLocationsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getDrLocationsOptions,
      "getDrLocationsOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getDrLocationsOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/dr_locations/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getDrLocations");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getDrLocationsOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getDrLocationsOptions.acceptLanguage());
    }
    ResponseConverter<GetDrLocationsResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<GetDrLocationsResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get managed vms for the instance.
   *
   * Retrieves the list of disaster recovery (DR) managed virtual machines for the specified service instance.
   *
   * @param getDrManagedVmOptions the {@link GetDrManagedVmOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ManagedVmMapResponse}
   */
  public ServiceCall<ManagedVmMapResponse> getDrManagedVm(GetDrManagedVmOptions getDrManagedVmOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getDrManagedVmOptions,
      "getDrManagedVmOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getDrManagedVmOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/dr_managed_vms/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getDrManagedVm");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getDrManagedVmOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getDrManagedVmOptions.acceptLanguage());
    }
    ResponseConverter<ManagedVmMapResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ManagedVmMapResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Disaster recovery deployment details.
   *
   * Retrieves the disaster recovery (DR) summary details for the specified service instance, including key
   * configuration, status information and managed vm details.
   *
   * @param getDrSummaryOptions the {@link GetDrSummaryOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link DrAutomationGetSummaryResponse}
   */
  public ServiceCall<DrAutomationGetSummaryResponse> getDrSummary(GetDrSummaryOptions getDrSummaryOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getDrSummaryOptions,
      "getDrSummaryOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getDrSummaryOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/dr_summary/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getDrSummary");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getDrSummaryOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getDrSummaryOptions.acceptLanguage());
    }
    ResponseConverter<DrAutomationGetSummaryResponse> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<DrAutomationGetSummaryResponse>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get MachineTypes based on selected workspaces.
   *
   * Retrieves the list of supported machine types for the given workspace. This endpoint is used to identify machine
   * types available for disaster recovery automation.
   *
   * @param getMachineTypeOptions the {@link GetMachineTypeOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link MachineTypesByWorkspace}
   */
  public ServiceCall<MachineTypesByWorkspace> getMachineType(GetMachineTypeOptions getMachineTypeOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getMachineTypeOptions,
      "getMachineTypeOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getMachineTypeOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/machinetypes/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getMachineType");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getMachineTypeOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getMachineTypeOptions.acceptLanguage());
    }
    builder.query("primary_workspace_name", String.valueOf(getMachineTypeOptions.primaryWorkspaceName()));
    if (getMachineTypeOptions.standbyWorkspaceName() != null) {
      builder.query("standby_workspace_name", String.valueOf(getMachineTypeOptions.standbyWorkspaceName()));
    }
    ResponseConverter<MachineTypesByWorkspace> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<MachineTypesByWorkspace>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * List of primary and standby powervs workspaces.
   *
   * Retrieves the power virtual server workspaces for primary and standby orchestrator based on location id.
   *
   * @param getPowervsWorkspacesOptions the {@link GetPowervsWorkspacesOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link DrData}
   */
  public ServiceCall<DrData> getPowervsWorkspaces(GetPowervsWorkspacesOptions getPowervsWorkspacesOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getPowervsWorkspacesOptions,
      "getPowervsWorkspacesOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getPowervsWorkspacesOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/powervs_workspaces/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getPowervsWorkspaces");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    builder.query("location_id", String.valueOf(getPowervsWorkspacesOptions.locationId()));
    ResponseConverter<DrData> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<DrData>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Create DR Deployment.
   *
   * Creates DR Deployment by creating Orchestrator instance in the given PowerVS workspace and configuration.
   * Orchestrator instance can be used to manage multiple virtual servers and ensure continuous availability. For more
   * details, refer Deploying the Orchestrator -
   * https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-idep-the-orch.
   *
   * @param createManageDrOptions the {@link CreateManageDrOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ServiceInstanceManageDR}
   */
  public ServiceCall<ServiceInstanceManageDR> createManageDr(CreateManageDrOptions createManageDrOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(createManageDrOptions,
      "createManageDrOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", createManageDrOptions.instanceId());
    RequestBuilder builder = RequestBuilder.post(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/manage_dr/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "createManageDr");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (createManageDrOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", createManageDrOptions.acceptLanguage());
    }
    if (createManageDrOptions.standByRedeploy() != null) {
      builder.query("stand_by_redeploy", String.valueOf(createManageDrOptions.standByRedeploy()));
    }
    if (createManageDrOptions.acceptsIncomplete() != null) {
      builder.query("accepts_incomplete", String.valueOf(createManageDrOptions.acceptsIncomplete()));
    }
    final JsonObject contentJson = new JsonObject();
    contentJson.addProperty("location_id", createManageDrOptions.locationId());
    contentJson.addProperty("machine_type", createManageDrOptions.machineType());
    contentJson.addProperty("orchestrator_location_type", createManageDrOptions.orchestratorLocationType());
    contentJson.addProperty("orchestrator_name", createManageDrOptions.orchestratorName());
    contentJson.addProperty("orchestrator_password", createManageDrOptions.orchestratorPassword());
    contentJson.addProperty("orchestrator_workspace_id", createManageDrOptions.orchestratorWorkspaceId());
    if (createManageDrOptions.apiKey() != null) {
      contentJson.addProperty("api_key", createManageDrOptions.apiKey());
    }
    if (createManageDrOptions.clientId() != null) {
      contentJson.addProperty("client_id", createManageDrOptions.clientId());
    }
    if (createManageDrOptions.clientSecret() != null) {
      contentJson.addProperty("client_secret", createManageDrOptions.clientSecret());
    }
    if (createManageDrOptions.guid() != null) {
      contentJson.addProperty("guid", createManageDrOptions.guid());
    }
    if (createManageDrOptions.orchestratorHa() != null) {
      contentJson.addProperty("orchestrator_ha", createManageDrOptions.orchestratorHa());
    }
    if (createManageDrOptions.proxyIp() != null) {
      contentJson.addProperty("proxy_ip", createManageDrOptions.proxyIp());
    }
    if (createManageDrOptions.regionId() != null) {
      contentJson.addProperty("region_id", createManageDrOptions.regionId());
    }
    if (createManageDrOptions.resourceInstance() != null) {
      contentJson.addProperty("resource_instance", createManageDrOptions.resourceInstance());
    }
    if (createManageDrOptions.secret() != null) {
      contentJson.addProperty("secret", createManageDrOptions.secret());
    }
    if (createManageDrOptions.secretGroup() != null) {
      contentJson.addProperty("secret_group", createManageDrOptions.secretGroup());
    }
    if (createManageDrOptions.sshKeyName() != null) {
      contentJson.addProperty("ssh_key_name", createManageDrOptions.sshKeyName());
    }
    if (createManageDrOptions.standbyMachineType() != null) {
      contentJson.addProperty("standby_machine_type", createManageDrOptions.standbyMachineType());
    }
    if (createManageDrOptions.standbyOrchestratorName() != null) {
      contentJson.addProperty("standby_orchestrator_name", createManageDrOptions.standbyOrchestratorName());
    }
    if (createManageDrOptions.standbyOrchestratorWorkspaceId() != null) {
      contentJson.addProperty("standby_orchestrator_workspace_id", createManageDrOptions.standbyOrchestratorWorkspaceId());
    }
    if (createManageDrOptions.standbyTier() != null) {
      contentJson.addProperty("standby_tier", createManageDrOptions.standbyTier());
    }
    if (createManageDrOptions.tenantName() != null) {
      contentJson.addProperty("tenant_name", createManageDrOptions.tenantName());
    }
    if (createManageDrOptions.tier() != null) {
      contentJson.addProperty("tier", createManageDrOptions.tier());
    }
    builder.bodyJson(contentJson);
    ResponseConverter<ServiceInstanceManageDR> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ServiceInstanceManageDR>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * View details of Last operation performed on the instance.
   *
   * Retrieves the status of the last operation performed on the specified service instance, such as provisioning,
   * updating, or deprovisioning.
   *
   * @param getLastOperationOptions the {@link GetLastOperationOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link ServiceInstanceStatus}
   */
  public ServiceCall<ServiceInstanceStatus> getLastOperation(GetLastOperationOptions getLastOperationOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getLastOperationOptions,
      "getLastOperationOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getLastOperationOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/last_operation/{instance_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getLastOperation");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getLastOperationOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getLastOperationOptions.acceptLanguage());
    }
    ResponseConverter<ServiceInstanceStatus> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<ServiceInstanceStatus>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get events from the cloud instance since a specific timestamp.
   *
   * Retrieves the list of events from the specified service instance ID.
   *
   * @param listEventsOptions the {@link ListEventsOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link EventCollection}
   */
  public ServiceCall<EventCollection> listEvents(ListEventsOptions listEventsOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(listEventsOptions,
      "listEventsOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", listEventsOptions.instanceId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/service_instances/{instance_id}/events", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "listEvents");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (listEventsOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", listEventsOptions.acceptLanguage());
    }
    if (listEventsOptions.time() != null) {
      builder.query("time", String.valueOf(listEventsOptions.time()));
    }
    if (listEventsOptions.fromTime() != null) {
      builder.query("from_time", String.valueOf(listEventsOptions.fromTime()));
    }
    if (listEventsOptions.toTime() != null) {
      builder.query("to_time", String.valueOf(listEventsOptions.toTime()));
    }
    ResponseConverter<EventCollection> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<EventCollection>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

  /**
   * Get a single event.
   *
   * Retrieves the details of a specific event for the given service instance provision ID.
   *
   * @param getEventOptions the {@link GetEventOptions} containing the options for the call
   * @return a {@link ServiceCall} with a result of type {@link Event}
   */
  public ServiceCall<Event> getEvent(GetEventOptions getEventOptions) {
    com.ibm.cloud.sdk.core.util.Validator.notNull(getEventOptions,
      "getEventOptions cannot be null");
    Map<String, String> pathParamsMap = new HashMap<String, String>();
    pathParamsMap.put("instance_id", getEventOptions.instanceId());
    pathParamsMap.put("event_id", getEventOptions.eventId());
    RequestBuilder builder = RequestBuilder.get(RequestBuilder.resolveRequestUrl(getServiceUrl(), "/drautomation/v1/service_instances/{instance_id}/events/{event_id}", pathParamsMap));
    Map<String, String> sdkHeaders = SdkCommon.getSdkHeaders("dr_automation_service", "v1", "getEvent");
    for (Entry<String, String> header : sdkHeaders.entrySet()) {
      builder.header(header.getKey(), header.getValue());
    }
    builder.header("Accept", "application/json");
    if (getEventOptions.acceptLanguage() != null) {
      builder.header("Accept-Language", getEventOptions.acceptLanguage());
    }
    ResponseConverter<Event> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<Event>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

}
